### ISSUE TITLE
ERROR: Missing JSON attribute: access_token

### ISSUE THREAD

**Issue by codenoid** [crystaljobs/api#1]
https://api.crystaljobs.org/oauth/github/callback?code=9d264683d2979cabb3e2&state=6058889bfdef3bfa89a1771557bac118

https://i.postimg.cc/jj3N2T6Z/Screenshot_from_2018-09-25_03-45-24.png

```
ERROR: Missing JSON attribute: access_token
  parsing GitHub::AccessToken at 1:1 (JSON::MappingError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???

```

**Comment by codenoid** [comment]
```
ERROR: Validation failed: {"website" => ["must be an HTTP(S) URI"]} (Validations::Error)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```

**Comment by vladfaust** [comment]
> ERROR: Missing JSON attribute: access_token

That's very strange, because https://github.com/crystaljobs/api/blob/27a4dce3dff729a8171d7daff2fa1d35b525a158/src/lib/github/client.cr#L22-L27

So it's 200 and access token still missing. How that's possible? :thinking:

**Comment by vladfaust** [comment]
Regarding to validation, 
![image](https://user-images.githubusercontent.com/7955682/45982067-f5056e00-c05f-11e8-8505-1f39d705723e.png)

You want to be fancy, that's an edge case. Your endpoint returns this: https://api.github.com/users/codenoid. Gonna handle this crazy scenario. For now, you can change your website so it gonna pass validation.

**Comment by vladfaust** [comment]
I've added errors logging in 3b77f775e2610f173baa0d79fcfa21f212d4dddd :sweat_smile:
